package m84_spring_data_jpa_migrations.practice.task07;

/**
 * Задача 07 — Модуль 84: МИНИ-ПРОЕКТ «Production-ready товар shop-data-jpa»
 *
 * ТРЕБУЮТСЯ ЗАВИСИМОСТИ:
 *   org.springframework.boot:spring-boot-starter-data-jpa:3.2.x, org.flywaydb:flyway-core,
 *   com.h2database:h2 (см. theory.md).
 *
 * ЦЕЛЬ: собрать сущность «как в проде»: схема под управлением Flyway (validate),
 *       оптимистичная блокировка @Version с РЕТРАЕМ конфликта, аудит через
 *       общий @MappedSuperclass.
 *
 * ЗАДАНИЕ (всё в одном файле + один файл миграции):
 *
 *   1) Миграция src/main/resources/db/migration/V1__create_products.sql:
 *        CREATE TABLE products (
 *            id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *            name       VARCHAR(255) NOT NULL,
 *            stock      INT NOT NULL,
 *            version    BIGINT NOT NULL DEFAULT 0,
 *            created_at TIMESTAMP, updated_at TIMESTAMP,
 *            created_by VARCHAR(64), updated_by VARCHAR(64)
 *        );
 *      В application.properties: spring.jpa.hibernate.ddl-auto=validate (схему ведёт Flyway!).
 *
 *   2) @MappedSuperclass Auditable07 с полями @CreatedDate/@LastModifiedDate/
 *      @CreatedBy/@LastModifiedBy и @EntityListeners(AuditingEntityListener.class).
 *      Product07 extends Auditable07 + @Version private long version.
 *
 *   3) AppConfig07: @EnableJpaAuditing + AuditorAware<String> (вернёт "system").
 *
 *   4) InventoryService07.purchase(id, qty): @Transactional — уменьшить stock на qty,
 *      бросить IllegalStateException при нехватке. Версия инкрементится автоматически.
 *
 *   5) InventoryService07.purchaseWithRetry(id, qty, attempts): при
 *      ObjectOptimisticLockingFailureException — повторить (re-read + retry) до attempts раз.
 *      (демонстрация стратегии обработки конфликта оптимистичной блокировки.)
 *
 *   6) Runner07: засейте товар stock=10; выполните purchase(1) → stock 9, version 1;
 *      выведите createdAt/createdBy/updatedAt/updatedBy и version.
 *
 * АРХИТЕКТУРА:
 *
 *   Flyway (V1) → схема           ddl-auto=validate → Hibernate сверяет
 *        │
 *   Product07 ──extends── Auditable07 (@MappedSuperclass: created/updated by/at)
 *        │  @Version → защита от потерянных обновлений
 *        │
 *   purchaseWithRetry() ── ловит ObjectOptimisticLockingFailureException → re-read + retry
 *
 * ОЖИДАЕМЫЙ ИТОГ:
 *   после purchase(1): stock=9, version=1, createdAt/createdBy заполнены ("system"),
 *   updatedAt обновлён.
 *
 * ПОДСКАЗКА: соберите Task04 (@Version), Task05 (обработка конфликта), Task06 (аудит)
 *            и Task01 (миграция). Аудит-поля — в базовом классе, чтобы переиспользовать.
 */

import jakarta.persistence.*;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.dao.OptimisticLockingFailureException;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.domain.AuditorAware;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.Instant;
import java.util.Optional;

public class Task07 {
    public static void main(String[] args) {
        SpringApplication.run(Task07.class, args);
    }
}
